# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Run UI Tests"
  lane :ui_tests do
#scan
    run_tests(
      project: "IntegrationTestDemo.xcodeproj",
      scheme: "IntegrationTestDemo",                    # Replace with your scheme name
      devices: ["iPhone 16"],
      clean: true,
      output_directory: "./fastlane/test_output",
      output_types: "html,junit",
      result_bundle: true,
      derived_data_path: "./fastlane/derived_data",
      fail_build: false,    # so CI completes even if tests fail
      code_coverage: false
    )
  end
end
