# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Run UI Tests"
  lane :ui_tests do
    scan(
      workspace: "IntegrationTestDemo.xcworkspace",
      scheme: "IntegrationTestDemo",                    # Replace with your scheme name
      devices: ["iPhone 15"],
      clean: true,
      output_directory: "./fastlane/test_output",
      output_types: "html,junit",result_bundle: true
    )
  end
end
